version: 2.1
jobs:
  build:
    working_directory: ~/SWE_Project1/NewApp/testapp1
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: CHECK1
          command: |
            pwd
            ls
      - run:
          name: CHECK2
          command: ls
      - run:
          name: CHECK3
          command: cd NewApp
      - run:
          name: CHECK4
          command: ls
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Tests
          command: npm test

workflows:
  basic:
    jobs:
      - build
