version: 2.1
jobs:
  build:
    working_directory: ~/SWE_Project1/NewApp/testapp1
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: |
            cd NewApp/testapp1
            npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Tests
          command: |
            cd NewApp/testapp1
            npm test

workflows:
  basic:
    jobs:
      - build
