version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      
      - run:
          name: magic command
          command: npm install react-scripts --save

      - restore_cache:
         keys:
            - v1-dependencies-{{checksum "package.json"}}
            - v1-dependencies-

      - run:
          name: Install npm dependencies
          command: npm install --save
            

      - save_cache:
          paths:
            -node_modules
          key: v1-dependencies-{{checksum "package.json"}}

      - run:
          name: run unit tests
          command: npm run
workflows:
  build_test:
    jobs:
      - run_tests