version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command:
            npm install --no-package-lock
      - run:
          name: run unit tests
          command:
            npm test
workflows:
  build_test:
    jobs:
      - run_tests
      

