version: 2.1
jobs:
  build:
    working_directory: ~/SWE_Project1
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: magic command
          command: npm install react-scripts --save
      - run:
          name: Install Dependencies
          command: |
            cd NewApp/testapp1
            npm ci
      - run:
          name: Run Tests
          command: |
            cd NewApp/testapp1
            npm test

workflows:
  basic:
    jobs:
      - build
